spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://192.168.0.102:3306/blog_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      stat-view-servlet:
        login-username: admin
        login-password: admin